Adding latest binaries

diff --git a/objects/setup-node b/objects/setup-node
--- a/objects/setup-node
+++ b/objects/setup-node
@@ -6,8 +6,8 @@ r_number="$2"
 
 if [ "$r_type" = router ]
 then
-    sudo sysctl -w "net.ipv4.conf.all.forwarding=1"
-    sudo sysctl -w "net.ipv6.conf.all.forwarding=1"
+    sudo sysctl -w "net.ipv4.conf.all.forwarding=1" >/dev/null
+    sudo sysctl -w "net.ipv6.conf.all.forwarding=1" >/dev/null
 fi
 
 sudo cp -a /tmp/experiment/lib* /usr/local/lib/
@@ -20,16 +20,22 @@ sudo cp -a /tmp/experiment/librecast* /usr/local/include/
 sudo cp -a /tmp/experiment/lwmon.h /usr/local/include/
 sudo mkdir -p /usr/local/include/lwmon
 sudo cp -a /tmp/experiment/lwmon-include/* /usr/local/include/lwmon/
+sudo ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
+sudo sed -i -e 's/\<us\.archive/be.archive/' /etc/apt/sources.list
 sudo ldconfig
+
+chmod 600 /tmp/experiment/id_rsa
+cp /tmp/experiment/id_rsa* $HOME/.ssh
 
 # update host table to have more useful list of nodes than the
 # one we get from the testbed
-egrep -v '^192\.168\.|^fd' /etc/hosts > /tmp/hosts
+egrep -vi '^192\.168\.|^fd|^fe80:' /etc/hosts > /tmp/hosts
 cat /tmp/experiment/hosts >> /tmp/hosts
 sudo cp /tmp/hosts /etc/hosts
 
 # find all IP addresses this node needs, and on which interfaces
 code=0
+lname=c
 > /tmp/interface
 while read what type number hwaddr ipv4 ipv6
 do
@@ -40,10 +46,10 @@ do
 		awk -F/ '{print $(NF-1); exit}'`"
     if [ ".$interface" = . ]
     then
-	echo "Cannot figure out interface name"
+	echo "Cannot figure out interface name" >&2
 	code=1
     fi
-    echo "$interface  $ipv4  $ipv6"
+    printf '%-10s %-16s %s\n' "$interface" "$ipv4" "$ipv6" >&2
     ip addr show dev "$interface" | \
     awk '($1 == "inet" || $1 == "inet6") && /scope global/ {print $2}' | \
     while read oldaddr
@@ -51,19 +57,41 @@ do
 	sudo ip addr delete "$oldaddr" dev "$interface"
     done
     sudo ip link set down dev "$interface"
+    echo "$interface" >> /tmp/interface
     sudo ip link set up dev "$interface"
+    # wait for link-local addresses and output /etc/hosts fragment for them
+    addrs=`ip -6 addr list scope link dev "$interface" | \
+	   awk '$1 == "inet6" {gsub("/[0-9]*$", "", $2); print $2}'`
+    while [ ".$addrs" = . ]
+    do
+	sleep 0.2
+	addrs=`ip -6 addr list scope link dev "$interface" | \
+	       awk '$1 == "inet6" {gsub("/[0-9]*$", "", $2); print $2}'`
+    done
+    if [ "$r_type" = router ]
+    then
+	hname="$r_type$r_number$lname $r_type$r_number"
+	lname=s
+    else
+	hname="$r_type$r_number"
+    fi
+    for addr in $addrs
+    do
+	printf '%-30s %s\n' "$addr" "$hname"
+	echo "                            $addr" >&2
+    done
+    # now we can add IP addresses
     sudo ip -4 addr add "$ipv4/24" dev "$interface"
     sudo ip -6 addr add "$ipv6/64" dev "$interface" nodad
-    # this seem to be required to make network actually be up
-    ping -c1 -n -W1 "$ipv4" > /dev/null 2>&1
-    ping -c1 -n -W1 "$ipv6" > /dev/null 2>&1
-    ping -c1 -n -W1 -6 director0 > /dev/null 2>&1
-    ping -c1 -n -W1 -6 server0 > /dev/null 2>&1
-    echo "$interface" >> /tmp/interface
+    # routers need to actually route packets
     [ "$type" = router ] || continue
-    sudo sysctl -w "net.ipv4.conf.$interface.forwarding=1"
-    sudo sysctl -w "net.ipv6.conf.$interface.forwarding=1"
+    sudo sysctl -w "net.ipv4.conf.$interface.forwarding=1" >/dev/null
+    sudo sysctl -w "net.ipv6.conf.$interface.forwarding=1" >/dev/null
 done < /tmp/experiment/setup-data
+
+# just making sure...
+ping -c1 -n -W1 -6 director0 > /dev/null 2>&1
+ping -c1 -n -W1 -6 server0 > /dev/null 2>&1
 
 # see if we need to set up any other routes
 while read what type number rto via
